FROM ubuntu:20.04
RUN apt-get -y update

RUN apt-get install wget xz-utils -y

# for creating an ISO
RUN apt-get install mkisofs -y

# for formatting filesystem of a raw image
RUN apt-get install e2fsprogs -y